---
# Configure VM for stack installation / app deployment

- name: install msmtp
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
    - exim4

- name: create config
  template: src=etc/exim4/update-exim4.conf.conf.j2 dest=/etc/exim4/update-exim4.conf.conf owner=root group=root mode=644

- name: update configuration
  command: "update-exim4.conf"
  notify:
    - Start EXIM
